import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./shared/Footer/Footer";
import Navbar from "./shared/Navbar/Navbar";
import React from "react";
import { Providers } from "./providers";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mohammad Ebrahim",
  description: "Generated by create next app",
};

// const DynamicNavbar = dynamic(() => import(`./shared/Navbar/Navbar`), {
//   ssr: false,
// });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </body>
      </Providers>
    </html>
  );
}
